# Generated by Django 3.2.16 on 2022-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20221205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, default='Пример отзыва', max_length=500, verbose_name='отзыв'),
        ),
    ]
