# Generated by Django 3.2.16 on 2022-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20221208_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Ненависть'), (2, '2 - Неприязнь'), (3, '3 - Нейтрально'), (4, '4 - Обожание'), (5, '5 - Любовь')], null=True, verbose_name='оценка'),
        ),
    ]
