# Generated by Django 3.2.16 on 2022-12-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'оценка', 'verbose_name_plural': 'оценки'},
        ),
    ]
