# Generated by Django 3.2.16 on 2022-10-30 16:06

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20221030_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='Sample Text', validators=[catalog.validators.validate_words], verbose_name='Описание'),
        ),
    ]
