# Generated by Django 3.2.16 on 2022-10-31 10:37

import catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20221030_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Слаг категории', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', "Разрешены только цифры, буквы латиницы,символы '-' и '_'")], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=100, help_text='Вес категории', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32766)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(help_text='Категория товара', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Теги товара', to='catalog.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='Sample Text', help_text='Описание товара', validators=[catalog.validators.validate_words], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(help_text='Слаг тега', max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-_]*$', "Разрешены только цифры, буквы латиницы,символы '-' и '_'")], verbose_name='Слаг'),
        ),
    ]
