# Generated by Django 3.2.16 on 2022-11-09 15:28

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_item_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryimage',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='Sample Text', help_text='Описание товара', validators=[catalog.validators.validate_words], verbose_name='Описание'),
        ),
    ]
