# Generated by Django 3.2.16 on 2022-11-09 16:14

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20221109_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondaryimage',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(default='Sample Text', help_text='Описание товара', validators=[catalog.validators.validate_words], verbose_name='Описание'),
        ),
    ]
