# Generated by Django 3.2.16 on 2022-12-05 14:42

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20221205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг', max_length=200, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(blank=True, default=100, help_text='Вес категории', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32766)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(blank=True, default='Sample Text', help_text='Описание товара', validators=[catalog.validators.validate_words], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='secondaryimage',
            name='name',
            field=models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, default='Sample name', max_length=150, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Слаг', max_length=200, unique=True, verbose_name='слаг'),
        ),
    ]
